### PR TITLE
Revert "Update to rc1"

### PR DESCRIPTION
**Pull request by andrewnicols**
RC1 is currently very unstable.
See https://github.com/Microsoft/mssql-docker/issues/126 for info.

This reverts commit dfb499a75de9474732af72bbbd102dd676c2aacf.

### CODE REVIEW

**Comment by andrewnicols** [comment]
Just to note that this is currently preventing me from running builds.

Maybe it's worth tagging builds too. I currently can't easily revert to an older build.

**Comment by scara** [comment]
Hi @andrewnicols,
that's strange: I'm running it fine in 17.06 CE on (several) CentOS 7.3 (1611) hosts.
Worth noting that each image has an expiration date, in CTP 2.1<sup>[1](#exp-rc1)</sup> that means (today):
```
This is an evaluation version.  There are [91] days left in the evaluation period.
...
```
pretty enough (I hope 😉) to expect a workaround/_rc2_ addressing Microsoft/mssql-docker#126.

<sup><a id="exp-rc1">1</a></sup> RC1: (today) `This is an evaluation version.  There are [151] days left in the evaluation period.`

**Comment by andrewnicols** [comment]
Hi Matteo,

Yup - it's inconsistent. For me it fails on some brand new installs and is fine on others.

I'm running Ubuntu 16.04 with x86_64 arch and can get consistent, repeatable fails. Makes it totally useless as is for me and I'd rather we went back to a reliable release for now.

**Comment by danpoltawski** [comment]
I think we can just make a branch at this point and I can make it become a tagged build (maybe already) rather than needing to revert this

**Comment by danpoltawski** [comment]
ctp2-1 is rebuilding now: https://hub.docker.com/r/danpoltawski/moodle-db-mssql/builds/b4epttjdrad7g84wdkpsk84/

**Comment by danpoltawski** [comment]
I'm clsoing this because I think the tag achieves this

**Pull request closed without merging**
